name: vacancy_portal

services:
  app:
    image: akhaizel/vacancy_portal
    build: .
    environment:
      - DATABASE_URL=postgresql://prod_user:prod_password@db_prod:5432/prod_db
    ports:
      - "8000:8000"
    depends_on:
      - db_prod
    volumes:
      - .:/app

  db_prod:
    image: postgres:latest
    container_name: prod_postgres
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
      POSTGRES_DB: prod_db
    ports:
      - "5432:5432"
    volumes:
      - db_prod_data:/var/lib/postgresql/data

volumes:
  db_prod_data:
