"""add_organization_id_to_tenants_users_documents

Revision ID: 0bae74314d6d
Revises: 3fddb4d14498
Create Date: 2025-07-16 14:53:58.370520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0bae74314d6d'
down_revision: Union[str, None] = '3fddb4d14498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('tenants', sa.Column('organization_id', sa.Integer(), nullable=True))

    # Create a default organization if none exists, using the first available user
    op.execute("""
        INSERT INTO organizations (business_name, address, number_of_beds, role, owner_id)
        SELECT 'Default Organization', '123 Default St', 10, 'owner', (SELECT MIN(id) FROM users)
        WHERE NOT EXISTS (SELECT 1 FROM organizations LIMIT 1)
        AND EXISTS (SELECT 1 FROM users LIMIT 1)
    """)

    # Update existing tenants to belong to the first organization
    op.execute("""
        UPDATE tenants
        SET organization_id = (SELECT MIN(id) FROM organizations)
        WHERE organization_id IS NULL
    """)

    # Now make it NOT NULL
    op.alter_column('tenants', 'organization_id', nullable=False)

    # Add foreign key constraint
    op.create_foreign_key(None, 'tenants', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'organization_id')
    # ### end Alembic commands ###
