"""remove redundant field in Organization table

Revision ID: 3fddb4d14498
Revises: d96a5b8687a8
Create Date: 2025-06-26 02:52:41.599398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fddb4d14498'
down_revision: Union[str, None] = 'd96a5b8687a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'operator_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('operator_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
