"""remove role attribute from Organization table

Revision ID: 7b398ba70930
Revises: 0bae74314d6d
Create Date: 2025-07-21 15:28:02.912772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b398ba70930'
down_revision: Union[str, None] = '0bae74314d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
